### ISSUE TITLE
EZ Flash 3in1 rumble support

### ISSUE THREAD

**Issue by zerofalcon** [afska/piugba#27]
Hi!
This is an amazing port for the gba, I tried almost every feature and it works great.
My issue (more like a petition/enhancement, sorry) is that I am using an ez flash 3 in 1, so, the rumble feature is not supported.
The source code for enabling rumble on this flashcart is well documented, any chance rumble for the ez3in1 can be added to your game?
Thanks in advanced!

**Comment by afska** [comment]
Hi @zerofalcon 

I made this patch:
https://github.com/afska/piugba/compare/master...patch_ezf3i1_rumble
[patch_ezf3i1_rumble.zip](https://github.com/user-attachments/files/15846371/patch_ezf3i1_rumble.zip)

I don't have a 3-in-1 for testing, so let me know if it works!

**Comment by zerofalcon** [comment]
> Hi @zerofalcon
> 
> I made this patch: [master...patch_ezf3i1_rumble](https://github.com/afska/piugba/compare/master...patch_ezf3i1_rumble) [patch_ezf3i1_rumble.zip](https://github.com/user-attachments/files/15846371/patch_ezf3i1_rumble.zip)
> 
> I don't have a 3-in-1 for testing, so let me know if it works!

Thank you so much! I did some test using different hardware (gba sp 001,gba sp 101, DS fat, DS lite) and everything is working great. I tried to play using a gameboy player but it seems only the cartridge rumble but not the gamecube controller, I guess Im missing information and gameboy player support is not implemented, right? Hope we can have rumble too someday for use on emulators. 
Again, thanks and keep up the good work!

**Comment by afska** [comment]
No problem! Glad it's working, and yeah, GB Player rumble is not implemented currently. 

It's a good idea though :) I can look into this for a next update.

**Comment by afska** [comment]
Btw @zerofalcon, I found that mGBA already supports cartridge rumble!

You only need to enable it in _Tools -> Game overrides_ before loading the game
![image](https://github.com/afska/piugba/assets/1631752/ea751f55-b396-4d3a-85a5-6bfb94c1d659)

Unfortunately it didn't work well on my setup even with a rumble test ROM (https://github.com/mgba-emu/mgba/issues/3232) but maybe with other controllers works correctly 😅

**Comment by zerofalcon** [comment]
Nice find! I didnt know mgba had cartridge rumble support. Unfortunately, I have same issues as you mentioned using a Nintendo Switch pro controller and a gamecube wii u adapter.

**Comment by afska** [comment]
Hey @zerofalcon, just FYI, Rumble in the new v1.11.0 should work fine on latest mGBA ([development versions](https://mgba.io/downloads.html#development-downloads))
